// Auto-generated by: npm run db:types
// Do not edit manually. Regenerate after schema changes.
// This placeholder will be replaced once Supabase is linked and schema is deployed.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
